# Generated by Django 5.1.7 on 2025-05-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentprogram',
            name='type',
            field=models.CharField(choices=[('A', 'Programa ERGE Erosiva'), ('B', 'Programa ERGE No Erosiva (NERD)'), ('C', 'Programa Reflujo Extraesofágico'), ('D', 'Programa Funcional / Hipersensibilidad'), ('E', 'Programa Síntomas sin Pruebas'), ('F', 'Programa Sin Síntomas')], max_length=1),
        ),
    ]
