# Generated by Django 5.1.7 on 2025-05-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_treatmentprogram_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentprogram',
            name='color_primary',
            field=models.CharField(default='#0077B6', help_text='Color primario del programa en formato HEX', max_length=7),
        ),
        migrations.AddField(
            model_name='treatmentprogram',
            name='color_secondary',
            field=models.CharField(default='#00B4D8', help_text='Color secundario del programa en formato HEX', max_length=7),
        ),
        migrations.AddField(
            model_name='treatmentprogram',
            name='detailed_content',
            field=models.TextField(blank=True, help_text='Contenido detallado del programa en formato HTML o markdown', null=True),
        ),
        migrations.AlterField(
            model_name='treatmentprogram',
            name='type',
            field=models.CharField(choices=[('A', 'Programa A - GerdQ y RSI positivos'), ('B', 'Programa B - GerdQ positivo, RSI negativo'), ('C', 'Programa C - GerdQ negativo, RSI positivo'), ('D', 'Programa D - GerdQ y RSI negativos')], max_length=1),
        ),
    ]
