# Generated by Django 5.1.7 on 2025-05-01 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_endoscopy_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bmi',
            field=models.FloatField(blank=True, help_text='Calculado automáticamente', null=True, verbose_name='Índice de Masa Corporal'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_altered_motility',
            field=models.CharField(choices=[('YES', 'Sí'), ('NO', 'No'), ('UNKNOWN', 'No lo sé')], default='UNKNOWN', max_length=10, verbose_name='Motilidad esofágica alterada'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_constipation',
            field=models.CharField(choices=[('YES', 'Sí'), ('NO', 'No'), ('UNKNOWN', 'No lo sé')], default='UNKNOWN', max_length=10, verbose_name='Estreñimiento o esfuerzo al defecar'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_dry_mouth',
            field=models.CharField(choices=[('YES', 'Sí'), ('NO', 'No'), ('UNKNOWN', 'No lo sé')], default='UNKNOWN', max_length=10, verbose_name='Salivación reducida / sequedad bucal'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_excess_weight',
            field=models.BooleanField(default=False, verbose_name='Tiene exceso de peso (IMC ≥ 25)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_slow_emptying',
            field=models.CharField(choices=[('YES', 'Sí'), ('NO', 'No'), ('UNKNOWN', 'No lo sé')], default='UNKNOWN', max_length=10, verbose_name='Vaciamiento gástrico lento (gastroparesia)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stress_affects',
            field=models.CharField(choices=[('YES', 'Sí, claramente'), ('SOMETIMES', 'A veces'), ('NO', 'No')], default='UNKNOWN', max_length=10, verbose_name='Estrés o ansiedad como agravantes'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='has_hernia',
            field=models.CharField(choices=[('YES', 'Sí'), ('NO', 'No'), ('UNKNOWN', 'No lo sé')], default='UNKNOWN', max_length=10, verbose_name='Hernia de hiato o cardias incompetente'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height_cm',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(240)], verbose_name='Altura (cm)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)], verbose_name='Peso (kg)'),
        ),
    ]
