# Generated by Django 5.1.7 on 2025-07-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userprofile_bmi_userprofile_has_altered_motility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alcohol_consumption',
            field=models.CharField(choices=[('YES', 'Sí'), ('OCCASIONALLY', 'Ocasionalmente'), ('NO', 'No')], default='NO', max_length=15, verbose_name='Consumo habitual de alcohol'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='h_pylori_status',
            field=models.CharField(choices=[('ACTIVE', 'Sí, actualmente activa'), ('TREATED', 'Sí, pero ya tratada'), ('NO', 'No'), ('UNKNOWN', 'No lo sé')], default='UNKNOWN', max_length=10, verbose_name='Infección por Helicobacter pylori'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_gastritis',
            field=models.CharField(choices=[('YES', 'Sí'), ('NO', 'No'), ('UNKNOWN', 'No lo sé')], default='UNKNOWN', max_length=10, verbose_name='Gastritis o inflamación gástrica diagnosticada'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_intestinal_disorders',
            field=models.CharField(choices=[('YES', 'Sí'), ('NO', 'No'), ('UNKNOWN', 'No lo sé')], default='UNKNOWN', max_length=10, verbose_name='Alteraciones intestinales (SIBO, disbiosis, SII, gases)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_smoker',
            field=models.CharField(choices=[('YES', 'Sí'), ('NO', 'No')], default='NO', max_length=10, verbose_name='Tabaquismo activo'),
        ),
    ]
