# Generated by Django 5.1.7 on 2025-07-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_userprofile_has_constipation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(choices=[('default', 'Sin avatar'), ('avatar1', 'Avatar 1'), ('avatar2', 'Avatar 2'), ('avatar3', 'Avatar 3'), ('avatar4', 'Avatar 4'), ('avatar5', 'Avatar 5')], default='default', max_length=20, verbose_name='Avatar del usuario'),
        ),
    ]
