# Generated by Django 5.1.7 on 2025-08-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phenotype',
            field=models.CharField(choices=[('EROSIVE', 'ERGE Erosiva'), ('NERD', 'ERGE No Erosiva (NERD)'), ('NERD_MIXED', 'ERGE No Erosiva Mixta'), ('EXTRAESOPHAGEAL', 'Reflujo Extraesofágico'), ('FUNCTIONAL', 'Perfil Funcional / Hipersensibilidad'), ('SYMPTOMS_NO_TESTS', 'Síntomas sin Pruebas'), ('EXTRAESOPHAGEAL_NO_TESTS', 'Síntomas Extraesofágicos sin Pruebas'), ('NO_SYMPTOMS', 'Sin Síntomas ni Pruebas'), ('UNDETERMINED', 'No Determinado')], default='UNDETERMINED', max_length=30, verbose_name='Fenotipo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='scenario',
            field=models.CharField(blank=True, choices=[('A', 'A - Endoscopia positiva'), ('B', 'B - NERD Mixto (Endo- pH+ GERDq+ RSI+)'), ('C', 'C - NERD (Endo- pH+ GERDq+ RSI-)'), ('D', 'D - Extraesofágico (Endo- pH+ GERDq- RSI+)'), ('E', 'E - Bienestar (Endo- pH+ GERDq- RSI-)'), ('F', 'F - Funcional (Endo- pH- GERDq+ RSI+)'), ('F2', 'F2 - Funcional (Endo- pH- GERDq+ RSI-)'), ('F3', 'F3 - Funcional (Endo- pH- GERDq- RSI+)'), ('F4', 'F4 - Bienestar (Endo- pH- GERDq- RSI-)'), ('G', 'G - Mixto sin pH (Endo- No pH GERDq+ RSI+)'), ('H', 'H - Digestivo sin pH (Endo- No pH GERDq+ RSI-)'), ('I', 'I - Extraesofágico sin pH (Endo- No pH GERDq- RSI+)'), ('J', 'J - Bienestar sin pH (Endo- No pH GERDq- RSI-)'), ('K', 'K - Mixto sin Endo (No Endo pH hecha GERDq+ RSI+)'), ('L', 'L - Digestivo sin Endo (No Endo pH hecha GERDq+ RSI-)'), ('M', 'M - Extraesofágico sin Endo (No Endo pH hecha GERDq- RSI+)'), ('N', 'N - Bienestar sin Endo (No Endo pH hecha GERDq- RSI-)'), ('O', 'O - Mixto sin pruebas (No pruebas GERDq+ RSI+)'), ('P', 'P - Digestivo sin pruebas (No pruebas GERDq+ RSI-)'), ('Q', 'Q - Extraesofágico sin pruebas (No pruebas GERDq- RSI+)'), ('R', 'R - Bienestar sin pruebas (No pruebas GERDq- RSI-)')], max_length=3, null=True, verbose_name='Escenario diagnóstico'),
        ),
    ]
