# Generated by Django 5.1.7 on 2025-06-17 14:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0003_treatmentprogram_color_primary_and_more'),
        ('questionnaires', '0002_habitquestion_habitrecommendation_habitoption_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleHabitAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Puntuación inicial')),
                ('priority_order', models.PositiveIntegerField(help_text='1 para el peor hábito, 5 para el quinto peor', verbose_name='Orden de prioridad')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.habitquestion')),
            ],
            options={
                'ordering': ['priority_order'],
            },
        ),
        migrations.CreateModel(
            name='UserCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.PositiveIntegerField(help_text='1 para el primer ciclo, 2 para el segundo, etc.', verbose_name='Número de ciclo')),
                ('start_date', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateTimeField(verbose_name='Fecha de fin')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('PENDING_RENEWAL', 'Pendiente de renovación'), ('COMPLETED', 'Completado'), ('EXPIRED', 'Expirado')], default='ACTIVE', max_length=20, verbose_name='Estado')),
                ('gerdq_score', models.IntegerField(blank=True, null=True)),
                ('rsi_score', models.IntegerField(blank=True, null=True)),
                ('phenotype', models.CharField(choices=[('EROSIVE', 'ERGE Erosiva'), ('NERD', 'ERGE No Erosiva (NERD)'), ('EXTRAESOPHAGEAL', 'Reflujo Extraesofágico'), ('FUNCTIONAL', 'Perfil Funcional / Hipersensibilidad'), ('SYMPTOMS_NO_TESTS', 'Síntomas sin Pruebas'), ('NO_SYMPTOMS', 'Sin Síntomas ni Pruebas'), ('UNDETERMINED', 'No Determinado')], default='UNDETERMINED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.treatmentprogram')),
                ('tracked_habits', models.ManyToManyField(through='cycles.CycleHabitAssignment', to='questionnaires.habitquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Ciclo de usuario',
                'verbose_name_plural': 'Ciclos de usuario',
                'ordering': ['-cycle_number'],
                'unique_together': {('user', 'cycle_number')},
            },
        ),
        migrations.CreateModel(
            name='CycleSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('has_hernia', models.CharField(default='UNKNOWN', max_length=10)),
                ('has_altered_motility', models.CharField(default='UNKNOWN', max_length=10)),
                ('has_slow_emptying', models.CharField(default='UNKNOWN', max_length=10)),
                ('has_dry_mouth', models.CharField(default='UNKNOWN', max_length=10)),
                ('has_constipation', models.CharField(default='UNKNOWN', max_length=10)),
                ('stress_affects', models.CharField(default='UNKNOWN', max_length=10)),
                ('endoscopy_result', models.CharField(default='NOT_DONE', max_length=20)),
                ('ph_monitoring_result', models.CharField(default='NOT_DONE', max_length=20)),
                ('habit_scores', models.JSONField(default=dict, help_text='Diccionario con habit_type: score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='cycles.usercycle')),
            ],
        ),
        migrations.AddField(
            model_name='cyclehabitassignment',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycles.usercycle'),
        ),
        migrations.AlterUniqueTogether(
            name='cyclehabitassignment',
            unique_together={('cycle', 'habit')},
        ),
    ]
