# Generated by Django 5.1.7 on 2025-05-01 16:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_type', models.CharField(choices=[('MEAL_SIZE', 'Cantidad de comida ingerida'), ('DINNER_TIME', 'Tiempo entre cena y acostarse'), ('LIE_DOWN', 'Acostarse tras comer'), ('NIGHT_SYMPTOMS', 'Síntomas nocturnos'), ('SMOKING', 'Consumo de tabaco'), ('ALCOHOL', 'Consumo de alcohol'), ('EXERCISE', 'Ejercicio físico regular'), ('AVOID_TRIGGERS', 'Evitar alimentos que sientan mal'), ('STRESS', 'Estrés y salud digestiva'), ('HYDRATION_MEALS', 'Hidratación durante las comidas'), ('HYDRATION_DAY', 'Hidratación general durante el día'), ('CHEWING', 'Masticación de los alimentos')], max_length=20, unique=True, verbose_name='Tipo de hábito')),
                ('text', models.CharField(max_length=255, verbose_name='Pregunta')),
                ('description', models.TextField(blank=True, verbose_name='Descripción adicional')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pregunta de hábito',
                'verbose_name_plural': 'Preguntas de hábitos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HabitRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_type', models.CharField(choices=[('MEAL_SIZE', 'Cantidad de comida ingerida'), ('DINNER_TIME', 'Tiempo entre cena y acostarse'), ('LIE_DOWN', 'Acostarse tras comer'), ('NIGHT_SYMPTOMS', 'Síntomas nocturnos'), ('SMOKING', 'Consumo de tabaco'), ('ALCOHOL', 'Consumo de alcohol'), ('EXERCISE', 'Ejercicio físico regular'), ('AVOID_TRIGGERS', 'Evitar alimentos que sientan mal'), ('STRESS', 'Estrés y salud digestiva'), ('HYDRATION_MEALS', 'Hidratación durante las comidas'), ('HYDRATION_DAY', 'Hidratación general durante el día'), ('CHEWING', 'Masticación de los alimentos')], max_length=20, verbose_name='Tipo de hábito')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Contenido de la recomendación')),
                ('min_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Puntuación mínima para activar')),
                ('max_score', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Puntuación máxima para activar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está activa')),
            ],
            options={
                'verbose_name': 'Recomendación de hábito',
                'verbose_name_plural': 'Recomendaciones de hábitos',
                'ordering': ['habit_type', 'min_score'],
            },
        ),
        migrations.CreateModel(
            name='HabitOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Texto de la opción')),
                ('value', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Valor (0-3)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questionnaires.habitquestion', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Opción de hábito',
                'verbose_name_plural': 'Opciones de hábitos',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserHabitAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('is_onboarding', models.BooleanField(default=True, verbose_name='Es parte del onboarding')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.habitquestion', verbose_name='Pregunta de hábito')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.habitoption', verbose_name='Opción seleccionada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_answers', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Respuesta de hábito del usuario',
                'verbose_name_plural': 'Respuestas de hábitos del usuario',
                'ordering': ['-answered_at'],
                'unique_together': {('user', 'question', 'is_onboarding')},
            },
        ),
    ]
