# Generated by Django 5.1.7 on 2025-06-08 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('notes', models.TextField(verbose_name='Notas del día')),
                ('all_habits_completed', models.BooleanField(default=True, verbose_name='Todos los hábitos completados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_notes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Nota diaria',
                'verbose_name_plural': 'Notas diarias',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
