# Generated by Django 5.1.7 on 2025-05-01 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BMI', 'Índice de Masa Corporal'), ('HERNIA', 'Hernia de hiato'), ('MOTILITY', 'Motilidad esofágica alterada'), ('EMPTYING', 'Vaciamiento gástrico lento'), ('SALIVA', 'Salivación reducida'), ('CONSTIPATION', 'Estreñimiento'), ('STRESS', 'Estrés o ansiedad'), ('PHENOTYPE', 'Fenotipo ERGE'), ('HABIT', 'Hábito específico')], max_length=20, verbose_name='Tipo de condición')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está activo')),
            ],
            options={
                'verbose_name': 'Tipo de recomendación',
                'verbose_name_plural': 'Tipos de recomendaciones',
            },
        ),
        migrations.CreateModel(
            name='ConditionalRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('condition_value', models.CharField(help_text="Valor específico que activa esta recomendación (ej: 'YES', 'BMI_OVER_25', 'EROSIVE')", max_length=50, verbose_name='Valor de la condición')),
                ('tools', models.TextField(blank=True, help_text='Lista separada por comas de herramientas sugeridas', verbose_name='Herramientas sugeridas')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está activa')),
                ('recommendation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='recommendations.recommendationtype', verbose_name='Tipo de recomendación')),
            ],
            options={
                'verbose_name': 'Recomendación condicional',
                'verbose_name_plural': 'Recomendaciones condicionales',
                'ordering': ['recommendation_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Ha sido leída')),
                ('is_prioritized', models.BooleanField(default=False, verbose_name='Es prioritaria')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.conditionalrecommendation', verbose_name='Recomendación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Recomendación de usuario',
                'verbose_name_plural': 'Recomendaciones de usuario',
                'ordering': ['-is_prioritized', '-assigned_at'],
            },
        ),
    ]
