# Generated by Django 5.1.7 on 2025-07-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_habitquestion_habitrecommendation_habitoption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='type',
            field=models.CharField(choices=[('GERDQ', 'Cuestionario GerdQ'), ('RSI', 'Índice de Síntomas de Reflujo (RSI)'), ('HABITS', 'Cuestionario de Hábitos'), ('CLINICAL', 'Factores Clínicos'), ('GENERAL', 'Datos Generales Onboarding')], default='GENERAL', max_length=10),
        ),
    ]
