# Generated by Django 5.1.7 on 2025-05-01 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionnaires', '0002_habitquestion_habitrecommendation_habitoption_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está activo')),
                ('is_promoted', models.BooleanField(default=False, verbose_name='Es promocionado')),
                ('target_score', models.IntegerField(default=3, verbose_name='Puntuación objetivo')),
                ('current_score', models.IntegerField(default=0, verbose_name='Puntuación actual')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackers', to='questionnaires.habitquestion', verbose_name='Hábito')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_trackers', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Seguimiento de hábito',
                'verbose_name_plural': 'Seguimientos de hábitos',
                'ordering': ['-is_promoted', 'habit'],
                'unique_together': {('user', 'habit')},
            },
        ),
        migrations.CreateModel(
            name='HabitStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0, verbose_name='Racha actual')),
                ('longest_streak', models.IntegerField(default=0, verbose_name='Racha más larga')),
                ('last_log_date', models.DateField(blank=True, null=True, verbose_name='Fecha del último registro')),
                ('tracker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to='habits.habittracker', verbose_name='Seguimiento')),
            ],
            options={
                'verbose_name': 'Racha de hábito',
                'verbose_name_plural': 'Rachas de hábitos',
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('completion_level', models.IntegerField(choices=[(0, 'No completado'), (1, 'Parcialmente completado'), (2, 'Mayormente completado'), (3, 'Completamente logrado')], default=0, verbose_name='Nivel de cumplimiento')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='habits.habittracker', verbose_name='Seguimiento')),
            ],
            options={
                'verbose_name': 'Registro de hábito',
                'verbose_name_plural': 'Registros de hábitos',
                'ordering': ['-date'],
                'unique_together': {('tracker', 'date')},
            },
        ),
    ]
