# Generated by Django 5.1.7 on 2025-06-29 14:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0001_initial'),
        ('gamification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medal',
            options={'ordering': ['required_cycle_number', 'week_number', 'order'], 'verbose_name': 'Medalla', 'verbose_name_plural': 'Medallas'},
        ),
        migrations.RemoveField(
            model_name='medal',
            name='required_month',
        ),
        migrations.RemoveField(
            model_name='userlevel',
            name='current_cycle_start',
        ),
        migrations.RemoveField(
            model_name='userlevel',
            name='current_month',
        ),
        migrations.RemoveField(
            model_name='userlevel',
            name='current_month_points',
        ),
        migrations.RemoveField(
            model_name='userlevel',
            name='total_points',
        ),
        migrations.RemoveField(
            model_name='usermedal',
            name='month_when_earned',
        ),
        migrations.AddField(
            model_name='dailypoints',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cycles.usercycle', verbose_name='Ciclo al que pertenece'),
        ),
        migrations.AddField(
            model_name='medal',
            name='required_cycle_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de ciclo requerido'),
        ),
        migrations.AddField(
            model_name='userlevel',
            name='current_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gamification_data', to='cycles.usercycle', verbose_name='Ciclo actual'),
        ),
        migrations.AddField(
            model_name='userlevel',
            name='current_cycle_points',
            field=models.IntegerField(default=0, verbose_name='Puntos del ciclo actual'),
        ),
        migrations.AddField(
            model_name='userlevel',
            name='total_points_all_time',
            field=models.IntegerField(default=0, verbose_name='Puntos totales históricos'),
        ),
        migrations.AddField(
            model_name='usermedal',
            name='cycle_earned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cycles.usercycle', verbose_name='Ciclo cuando se obtuvo'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Orden dentro del ciclo'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='required_points',
            field=models.IntegerField(verbose_name='Puntos requeridos en el ciclo'),
        ),
        migrations.CreateModel(
            name='CycleGamificationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points_earned', models.IntegerField(default=0)),
                ('final_level', models.CharField(max_length=20)),
                ('medals_earned_count', models.IntegerField(default=0)),
                ('best_streak', models.IntegerField(default=0)),
                ('active_days', models.IntegerField(default=0)),
                ('perfect_days', models.IntegerField(default=0)),
                ('cycle_ranking', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_summary', to='cycles.usercycle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resumen de Gamificación por Ciclo',
                'verbose_name_plural': 'Resúmenes de Gamificación por Ciclo',
            },
        ),
    ]
