# Generated by Django 5.1.7 on 2025-07-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_userprofile_alcohol_consumption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='has_constipation',
            field=models.CharField(choices=[('YES', 'Sí'), ('SOMETIMES', 'A veces'), ('NO', 'No')], default='NO', max_length=10, verbose_name='Estreñimiento o esfuerzo al defecar'),
        ),
    ]
