# Generated by Django 5.1.7 on 2025-06-29 14:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0001_initial'),
        ('gamification', '0003_auto_20250629_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypoints',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycles.usercycle', verbose_name='Ciclo al que pertenece'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='required_cycle_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de ciclo requerido'),
        ),
        migrations.AlterField(
            model_name='usermedal',
            name='cycle_earned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycles.usercycle', verbose_name='Ciclo cuando se obtuvo'),
        ),
    ]
