# Generated by Django 5.1.7 on 2025-07-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionalrecommendation',
            name='icon_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
