# Generated by Django 5.1.7 on 2025-07-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_conditionalrecommendation_icon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionalrecommendation',
            name='tools_title',
            field=models.CharField(blank=True, help_text='Título que aparecerá sobre las herramientas sugeridas', max_length=255, verbose_name='Título de herramientas'),
        ),
    ]
